spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/seniorhealth
    username: seniorhealth
    password: paSs1234Word
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:oracle:thin:@//localhost:1521/orcl
#    username: antonina
#    password: antonina
#    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update # auto create/update tables in db
  mail:
    host: smtp.gmail.com
    port: 587
    username: seniorhealth123@gmail.com
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

senior-health:
  minOptPressureSys: 100
  maxOptPressureSys: 130
  minOptPressureDia: 50
  maxOptPressureDia: 90
  optTemerature: 36.6
  optMood: 3